import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Plus, Save, Trash2 } from "lucide-react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const configs = {
  pos: { title: "PDV", description: "Selecione os dados da venda e finalize com poucos cliques.", endpoint: "sales", action: "Registrar venda", fields: [["product_name", "Produto", "text"], ["quantity", "Quantidade", "number"], ["total", "Total da venda", "number"], ["payment_method", "Forma de pagamento", "select", ["Débito", "Crédito", "PIX", "Dinheiro", "Voucher"]], ["customer_name", "Cliente (opcional)", "text"]] },
  products: { title: "Produtos", description: "Cadastre o custo de compra e receba uma sugestão de preço de venda.", endpoint: "products", action: "Cadastrar produto", fields: [["name", "Nome do produto", "text"], ["purchase_price", "Quanto você pagou", "number"], ["purchase_quantity", "Quantidade comprada", "number"], ["unit", "Unidade da compra", "select", ["unidade", "kg", "g", "litro", "ml"]], ["sale_price", "Preço de venda (opcional)", "number"], ["barcode", "Código de barras", "text"]] },
  ingredients: { title: "Ingredientes", description: "Cadastre o preço e a quantidade comprada para calcular o custo das receitas.", endpoint: "ingredients", action: "Cadastrar ingrediente", fields: [["name", "Nome do ingrediente", "text"], ["purchase_price", "Preço pago na compra", "number"], ["purchase_quantity", "Quantidade comprada", "number"], ["unit", "Unidade", "select", ["g", "kg", "ml", "litro", "unidade"]]] },
  customers: { title: "Clientes", description: "Cadastre clientes para manter um histórico organizado.", endpoint: "customers", action: "Cadastrar cliente", fields: [["name", "Nome completo", "text"], ["phone", "Telefone", "text"], ["email", "E-mail", "email"], ["address", "Endereço", "text"], ["notes", "Observações", "text"]] },
};

function Field({ definition, value, onChange, type }) {
  const [name, label, kind, options] = definition;
  return <label>{label}{kind === "select" ? <select data-testid={`${type}-${name}-select`} value={value || options[0]} onChange={(event) => onChange(name, event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select> : <input data-testid={`${type}-${name}-input`} required={name === "name" || name === "quantity" || name === "product_name" || name === "purchase_price" || name === "purchase_quantity"} type={kind} value={value || ""} onChange={(event) => onChange(name, kind === "number" && event.target.value ? Number(event.target.value) : event.target.value)} />}</label>;
}

function Records({ type, items }) {
  return <section className="records-panel"><div className="panel-heading"><div><p className="eyebrow">REGISTROS</p><h3>Dados cadastrados</h3></div><span data-testid={`${type}-record-count`} className="record-count">{items.length} registros</span></div>{items.length === 0 ? <div data-testid={`${type}-empty-state`} className="small-empty">Nenhum registro cadastrado.</div> : <div className="record-list">{items.map((item) => <div data-testid={`${type}-record-row`} className="record-row" key={item.id}><strong>{item.name || item.product_name}</strong><span>{item.created_at?.slice(0, 10)}</span></div>)}</div>}</section>;
}

function StandardModule({ type }) {
  const settings = configs[type]; const defaults = Object.fromEntries(settings.fields.filter((field) => field[2] === "select").map((field) => [field[0], field[3][0]])); const [form, setForm] = useState(defaults); const [items, setItems] = useState([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(() => axios.get(`${API}/${settings.endpoint}`, { withCredentials: true }).then(({ data }) => setItems(data)).catch(() => setItems([])), [settings.endpoint]);
  useEffect(() => { load(); }, [load]);
  const update = (name, value) => setForm({ ...form, [name]: value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setMessage(""); try { await axios.post(`${API}/${settings.endpoint}`, form, { withCredentials: true }); setForm(defaults); setMessage("Cadastro salvo com sucesso."); load(); } catch (error) { setMessage(error.response?.data?.detail || "Não foi possível salvar o cadastro."); } finally { setSaving(false); } };
  const saleOptions = type === "pos" ? <p className="form-hint">Pagamento rápido: escolha uma das opções disponíveis.</p> : null;
  const suggestion = type === "products" && form.purchase_price && form.purchase_quantity ? Number(form.purchase_price) / Number(form.purchase_quantity) * 2.5 : 0;
  return <div className="module-content"><div className="module-heading"><div><p className="eyebrow">CADASTRO</p><h1>{settings.title}</h1><p className="subtle">{settings.description}</p></div></div><section className="form-panel"><div className="panel-heading"><div><h3>Novo cadastro</h3><p>Preencha os dados abaixo para começar.</p></div><Plus size={20} /></div><form className="crud-form" onSubmit={submit}>{settings.fields.map((definition) => <Field key={definition[0]} definition={definition} value={form[definition[0]]} onChange={update} type={type} />)}{suggestion > 0 && <div data-testid="products-price-suggestion" className="cost-preview">Sugestão de preço de venda: <strong>R$ {suggestion.toFixed(2).replace(".", ",")}</strong></div>}{saleOptions}<button data-testid={`${type}-save-button`} className="primary-button" disabled={saving}><Save size={16} />{saving ? "Salvando..." : settings.action}</button></form>{message && <p data-testid={`${type}-form-message`} className="form-message">{message}</p>}</section><Records type={type} items={items} /></div>;
}

function RecipeModule() {
  const [ingredients, setIngredients] = useState([]); const [lines, setLines] = useState([{ ingredient_id: "", quantity: "" }]); const [form, setForm] = useState({ name: "", category: "", preparation: "", duration_minutes: "", yield_quantity: "" }); const [items, setItems] = useState([]); const [message, setMessage] = useState("");
  const load = useCallback(() => axios.get(`${API}/recipes`, { withCredentials: true }).then(({ data }) => setItems(data)).catch(() => setItems([])), []);
  useEffect(() => { axios.get(`${API}/ingredients`, { withCredentials: true }).then(({ data }) => setIngredients(data)).catch(() => {}); load(); }, [load]);
  const cost = useMemo(() => lines.reduce((total, line) => { const ingredient = ingredients.find((item) => item.id === line.ingredient_id); return total + (ingredient ? Number(ingredient.unit_cost) * Number(line.quantity || 0) : 0); }, 0), [ingredients, lines]);
  const updateLine = (index, key, value) => setLines(lines.map((line, current) => current === index ? { ...line, [key]: value } : line));
  const submit = async (event) => { event.preventDefault(); try { await axios.post(`${API}/recipes`, { ...form, duration_minutes: form.duration_minutes ? Number(form.duration_minutes) : null, yield_quantity: form.yield_quantity ? Number(form.yield_quantity) : null, ingredients: lines.filter((line) => line.ingredient_id && line.quantity).map((line) => ({ ...line, quantity: Number(line.quantity) })) }, { withCredentials: true }); setMessage("Receita salva com custo calculado."); setForm({ name: "", category: "", preparation: "", duration_minutes: "", yield_quantity: "" }); setLines([{ ingredient_id: "", quantity: "" }]); load(); } catch (error) { setMessage(error.response?.data?.detail || "Não foi possível salvar a receita."); } };
  return <div className="module-content"><div className="module-heading"><div><p className="eyebrow">PRODUÇÃO</p><h1>Receitas</h1><p className="subtle">Escolha ingredientes, informe quantidades e veja o custo estimado antes de produzir.</p></div></div><section className="form-panel"><div className="panel-heading"><div><h3>Nova receita</h3><p>Ingredientes e quantidades ficam separados para facilitar a conferência.</p></div></div><form className="crud-form" onSubmit={submit}><label>Nome da receita<input data-testid="recipes-name-input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Categoria<input data-testid="recipes-category-input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Tempo (minutos)<input data-testid="recipes-duration-input" type="number" value={form.duration_minutes} onChange={(e) => setForm({ ...form, duration_minutes: e.target.value })} /></label><label>Rendimento<input data-testid="recipes-yield-input" type="number" value={form.yield_quantity} onChange={(e) => setForm({ ...form, yield_quantity: e.target.value })} /></label><label className="full-field">Modo de preparo<input data-testid="recipes-preparation-input" value={form.preparation} onChange={(e) => setForm({ ...form, preparation: e.target.value })} /></label><div className="ingredient-lines full-field"><div className="line-heading"><b>Ingredientes da receita</b><button data-testid="recipes-add-ingredient-button" type="button" className="link-button" onClick={() => setLines([...lines, { ingredient_id: "", quantity: "" }])}><Plus size={15} /> Adicionar ingrediente</button></div>{lines.map((line, index) => <div className="ingredient-line" key={index}><select data-testid={`recipes-ingredient-${index}-select`} value={line.ingredient_id} onChange={(e) => updateLine(index, "ingredient_id", e.target.value)}><option value="">Selecione um ingrediente</option>{ingredients.map((ingredient) => <option value={ingredient.id} key={ingredient.id}>{ingredient.name}</option>)}</select><input data-testid={`recipes-quantity-${index}-input`} type="number" min="0" step="0.001" placeholder="Quantidade usada" value={line.quantity} onChange={(e) => updateLine(index, "quantity", e.target.value)} /><button data-testid={`recipes-remove-ingredient-${index}-button`} type="button" className="icon-button" onClick={() => setLines(lines.filter((_, current) => current !== index))}><Trash2 size={16} /></button></div>)}</div><div data-testid="recipes-cost-preview" className="cost-preview">Custo estimado desta receita: <strong>R$ {cost.toFixed(2).replace(".", ",")}</strong></div><button data-testid="recipes-save-button" className="primary-button"><Save size={16} /> Salvar receita</button></form>{message && <p data-testid="recipes-form-message" className="form-message">{message}</p>}</section><Records type="recipes" items={items} /></div>;
}

export default function CrudModule({ type }) { return type === "recipes" ? <RecipeModule /> : <StandardModule type={type} />; }