import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Banknote, CreditCard, Landmark, Minus, Plus, Save, Search, Smartphone, Ticket, Trash2, X } from "lucide-react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const configs = {
  pos: { title: "PDV", description: "Selecione os dados da venda e finalize com poucos cliques.", endpoint: "sales", action: "Registrar venda", fields: [["product_name", "Produto", "text"], ["quantity", "Quantidade", "number"], ["total", "Total da venda", "number"], ["payment_method", "Forma de pagamento", "select", ["Débito", "Crédito", "PIX", "Dinheiro", "Voucher"]], ["customer_name", "Cliente (opcional)", "text"]] },
  products: { title: "Produtos", description: "Cadastre o custo de compra e receba uma sugestão de preço de venda.", endpoint: "products", action: "Cadastrar produto", fields: [["name", "Nome do produto", "text"], ["category", "Categoria do PDV", "select", ["Bebidas", "Salgados", "Doces"]], ["purchase_price", "Quanto você pagou", "number"], ["purchase_quantity", "Quantidade comprada", "number"], ["unit", "Unidade da compra", "select", ["unidade", "kg", "g", "litro", "ml"]], ["sale_price", "Preço de venda (opcional)", "number"], ["barcode", "Código de barras", "text"]] },
  ingredients: { title: "Ingredientes", description: "Cadastre o preço e a quantidade comprada para calcular o custo das receitas.", endpoint: "ingredients", action: "Cadastrar ingrediente", fields: [["name", "Nome do ingrediente", "text"], ["purchase_price", "Preço pago na compra", "number"], ["purchase_quantity", "Quantidade comprada", "number"], ["unit", "Unidade", "select", ["g", "kg", "ml", "litro", "unidade"]]] },
  customers: { title: "Clientes", description: "Cadastre clientes para manter um histórico organizado.", endpoint: "customers", action: "Cadastrar cliente", fields: [["name", "Nome completo", "text"], ["phone", "Telefone", "text"], ["email", "E-mail", "email"], ["address", "Endereço", "text"], ["notes", "Observações", "text"]] },
};

function Field({ definition, value, onChange, type }) {
  const [name, label, kind, options] = definition;
  return <label>{label}{kind === "select" ? <select data-testid={`${type}-${name}-select`} value={value || options[0]} onChange={(event) => onChange(name, event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select> : <input data-testid={`${type}-${name}-input`} required={name === "name" || name === "quantity" || name === "product_name" || name === "purchase_price" || name === "purchase_quantity"} type={kind} value={value || ""} onChange={(event) => onChange(name, kind === "number" && event.target.value ? Number(event.target.value) : event.target.value)} />}</label>;
}

function Records({ type, items }) {
  return <section className="records-panel"><div className="panel-heading"><div><p className="eyebrow">REGISTROS</p><h3>Dados cadastrados</h3></div><span data-testid={`${type}-record-count`} className="record-count">{items.length} registros</span></div>{items.length === 0 ? <div data-testid={`${type}-empty-state`} className="small-empty">Nenhum registro cadastrado.</div> : <div className="record-list">{items.map((item) => <div data-testid={`${type}-record-row`} className="record-row" key={item.id}><strong>{item.name || item.product_name}</strong><span>{item.created_at?.slice(0, 10)}</span></div>)}</div>}</section>;
}

function StandardModule({ type }) {
  const settings = configs[type]; const defaults = Object.fromEntries(settings.fields.filter((field) => field[2] === "select").map((field) => [field[0], field[3][0]])); const [form, setForm] = useState(defaults); const [items, setItems] = useState([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(() => axios.get(`${API}/${settings.endpoint}`, { withCredentials: true }).then(({ data }) => setItems(data)).catch(() => setItems([])), [settings.endpoint]);
  useEffect(() => { load(); }, [load]);
  const update = (name, value) => setForm({ ...form, [name]: value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setMessage(""); try { await axios.post(`${API}/${settings.endpoint}`, form, { withCredentials: true }); setForm(defaults); setMessage("Cadastro salvo com sucesso."); load(); } catch (error) { setMessage(error.response?.data?.detail || "Não foi possível salvar o cadastro."); } finally { setSaving(false); } };
  const saleOptions = type === "pos" ? <p className="form-hint">Pagamento rápido: escolha uma das opções disponíveis.</p> : null;
  const suggestion = type === "products" && form.purchase_price && form.purchase_quantity ? Number(form.purchase_price) / Number(form.purchase_quantity) * 2.5 : 0;
  return <div className="module-content"><div className="module-heading"><div><p className="eyebrow">CADASTRO</p><h1>{settings.title}</h1><p className="subtle">{settings.description}</p></div></div><section className="form-panel"><div className="panel-heading"><div><h3>Novo cadastro</h3><p>Preencha os dados abaixo para começar.</p></div><Plus size={20} /></div><form className="crud-form" onSubmit={submit}>{settings.fields.map((definition) => <Field key={definition[0]} definition={definition} value={form[definition[0]]} onChange={update} type={type} />)}{suggestion > 0 && <div data-testid="products-price-suggestion" className="cost-preview">Sugestão de preço de venda: <strong>R$ {suggestion.toFixed(2).replace(".", ",")}</strong></div>}{saleOptions}<button data-testid={`${type}-save-button`} className="primary-button" disabled={saving}><Save size={16} />{saving ? "Salvando..." : settings.action}</button></form>{message && <p data-testid={`${type}-form-message`} className="form-message">{message}</p>}</section><Records type={type} items={items} /></div>;
}

function RecipeModule() {
  const [ingredients, setIngredients] = useState([]); const [lines, setLines] = useState([{ ingredient_id: "", quantity: "" }]); const [form, setForm] = useState({ name: "", category: "", preparation: "", duration_minutes: "", yield_quantity: "" }); const [items, setItems] = useState([]); const [message, setMessage] = useState("");
  const load = useCallback(() => axios.get(`${API}/recipes`, { withCredentials: true }).then(({ data }) => setItems(data)).catch(() => setItems([])), []);
  useEffect(() => { axios.get(`${API}/ingredients`, { withCredentials: true }).then(({ data }) => setIngredients(data)).catch(() => {}); load(); }, [load]);
  const cost = useMemo(() => lines.reduce((total, line) => { const ingredient = ingredients.find((item) => item.id === line.ingredient_id); return total + (ingredient ? Number(ingredient.unit_cost) * Number(line.quantity || 0) : 0); }, 0), [ingredients, lines]);
  const updateLine = (index, key, value) => setLines(lines.map((line, current) => current === index ? { ...line, [key]: value } : line));
  const submit = async (event) => { event.preventDefault(); try { await axios.post(`${API}/recipes`, { ...form, duration_minutes: form.duration_minutes ? Number(form.duration_minutes) : null, yield_quantity: form.yield_quantity ? Number(form.yield_quantity) : null, ingredients: lines.filter((line) => line.ingredient_id && line.quantity).map((line) => ({ ...line, quantity: Number(line.quantity) })) }, { withCredentials: true }); setMessage("Receita salva com custo calculado."); setForm({ name: "", category: "", preparation: "", duration_minutes: "", yield_quantity: "" }); setLines([{ ingredient_id: "", quantity: "" }]); load(); } catch (error) { setMessage(error.response?.data?.detail || "Não foi possível salvar a receita."); } };
  return <div className="module-content"><div className="module-heading"><div><p className="eyebrow">PRODUÇÃO</p><h1>Receitas</h1><p className="subtle">Escolha ingredientes, informe quantidades e veja o custo estimado antes de produzir.</p></div></div><section className="form-panel"><div className="panel-heading"><div><h3>Nova receita</h3><p>Ingredientes e quantidades ficam separados para facilitar a conferência.</p></div></div><form className="crud-form" onSubmit={submit}><label>Nome da receita<input data-testid="recipes-name-input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Categoria<input data-testid="recipes-category-input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Tempo (minutos)<input data-testid="recipes-duration-input" type="number" value={form.duration_minutes} onChange={(e) => setForm({ ...form, duration_minutes: e.target.value })} /></label><label>Rendimento<input data-testid="recipes-yield-input" type="number" value={form.yield_quantity} onChange={(e) => setForm({ ...form, yield_quantity: e.target.value })} /></label><label className="full-field">Modo de preparo<input data-testid="recipes-preparation-input" value={form.preparation} onChange={(e) => setForm({ ...form, preparation: e.target.value })} /></label><div className="ingredient-lines full-field"><div className="line-heading"><b>Ingredientes da receita</b><button data-testid="recipes-add-ingredient-button" type="button" className="link-button" onClick={() => setLines([...lines, { ingredient_id: "", quantity: "" }])}><Plus size={15} /> Adicionar ingrediente</button></div>{lines.map((line, index) => <div className="ingredient-line" key={index}><select data-testid={`recipes-ingredient-${index}-select`} value={line.ingredient_id} onChange={(e) => updateLine(index, "ingredient_id", e.target.value)}><option value="">Selecione um ingrediente</option>{ingredients.map((ingredient) => <option value={ingredient.id} key={ingredient.id}>{ingredient.name}</option>)}</select><input data-testid={`recipes-quantity-${index}-input`} type="number" min="0" step="0.001" placeholder="Quantidade usada" value={line.quantity} onChange={(e) => updateLine(index, "quantity", e.target.value)} /><button data-testid={`recipes-remove-ingredient-${index}-button`} type="button" className="icon-button" onClick={() => setLines(lines.filter((_, current) => current !== index))}><Trash2 size={16} /></button></div>)}</div><div data-testid="recipes-cost-preview" className="cost-preview">Custo estimado desta receita: <strong>R$ {cost.toFixed(2).replace(".", ",")}</strong></div><button data-testid="recipes-save-button" className="primary-button"><Save size={16} /> Salvar receita</button></form>{message && <p data-testid="recipes-form-message" className="form-message">{message}</p>}</section><Records type="recipes" items={items} /></div>;
}

const money = (value) => `R$ ${Number(value || 0).toFixed(2).replace(".", ",")}`;
const productPrice = (product) => Number(product.sale_price || product.suggested_sale_price || 0);
const paymentMethods = [["Dinheiro", Banknote], ["Débito", Landmark], ["Crédito", CreditCard], ["PIX", Smartphone], ["Vale", Ticket]];

function PaymentModal({ total, onClose, onConfirmed }) {
  const [payment, setPayment] = useState("Débito"); const [cpf, setCpf] = useState(""); const [customerName, setCustomerName] = useState(""); const [printReceipt, setPrintReceipt] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const confirm = async () => { setSaving(true); setError(""); try { await onConfirmed({ payment_method: payment, customer_document: cpf || null, customer_name: customerName || null, print_receipt: printReceipt }); } catch (err) { setError(err.response?.data?.detail || "Não foi possível registrar a venda."); setSaving(false); } };
  return <div className="pos-modal-overlay" onClick={onClose}><div data-testid="pos-payment-modal" className="pos-modal" onClick={(event) => event.stopPropagation()}><div className="pos-modal-head"><h2>Fechar pedido</h2><button data-testid="pos-modal-close" className="icon-button" onClick={onClose} aria-label="Fechar"><X size={18} /></button></div><div className="pos-modal-total"><span>Total a pagar</span><strong data-testid="pos-modal-total">{money(total)}</strong></div><p className="pos-modal-label">Forma de pagamento</p><div className="payment-grid">{paymentMethods.map(([method, Icon]) => <button data-testid={`pos-payment-${method.toLowerCase()}`} className={payment === method ? "payment-option active" : "payment-option"} onClick={() => setPayment(method)} key={method}><Icon size={20} /><span>{method}</span></button>)}</div><div className="pos-modal-fields"><label>CPF/CNPJ na nota (opcional)<input data-testid="pos-cpf-input" placeholder="000.000.000-00" value={cpf} onChange={(event) => setCpf(event.target.value)} /></label><label>Nome (opcional)<input data-testid="pos-customer-name-input" placeholder="Aparece na nota" value={customerName} onChange={(event) => setCustomerName(event.target.value)} /></label></div><p className="pos-modal-hint">Cobre o valor exato do pedido na maquininha.</p><label className="pos-modal-check"><input data-testid="pos-print-receipt-checkbox" type="checkbox" checked={printReceipt} onChange={(event) => setPrintReceipt(event.target.checked)} />Imprimir cupom fiscal</label>{error && <p data-testid="pos-modal-error" className="form-message error">{error}</p>}<div className="pos-modal-actions"><button data-testid="pos-modal-cancel" className="ghost-button" onClick={onClose}>Cancelar</button><button data-testid="pos-modal-confirm" className="primary-button" onClick={confirm} disabled={saving}>{saving ? "Registrando..." : "Confirmar"}</button></div></div></div>;
}

function PosModule() {
  const fixedCategories = ["Bebidas", "Salgados", "Doces"];
  const [products, setProducts] = useState([]); const [category, setCategory] = useState("Bebidas"); const [search, setSearch] = useState(""); const [cart, setCart] = useState([]); const [checkout, setCheckout] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { axios.get(`${API}/products`, { withCredentials: true }).then(({ data }) => setProducts(data)).catch(() => setProducts([])); }, []);
  const categories = [...fixedCategories, ...products.map((product) => product.category).filter((item) => item && !fixedCategories.includes(item)).filter((item, index, all) => all.indexOf(item) === index)];
  const visibleProducts = products.filter((product) => product.category === category).filter((product) => !search || product.name.toLowerCase().includes(search.toLowerCase()));
  const total = cart.reduce((sum, line) => sum + line.unit_price * line.quantity, 0);
  const itemCount = cart.reduce((sum, line) => sum + line.quantity, 0);
  const addToCart = (product) => { setMessage(""); setCart((current) => { const found = current.find((line) => line.id === product.id); return found ? current.map((line) => line.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { id: product.id, product_name: product.name, unit_price: productPrice(product), quantity: 1 }]; }); };
  const changeQuantity = (id, delta) => setCart((current) => current.map((line) => line.id === id ? { ...line, quantity: line.quantity + delta } : line).filter((line) => line.quantity > 0));
  const confirmSale = async (extra) => { await axios.post(`${API}/sales`, { items: cart.map(({ product_name, quantity, unit_price }) => ({ product_name, quantity, unit_price })), total, ...extra }, { withCredentials: true }); setCart([]); setCheckout(false); setMessage("Venda registrada com sucesso."); };
  return <div className="pos-shell">{checkout && <PaymentModal total={total} onClose={() => setCheckout(false)} onConfirmed={confirmSale} />}<aside className="pos-rail"><p className="pos-rail-title">Categorias</p>{categories.map((item) => <button data-testid={`pos-category-${item.toLowerCase()}`} className={category === item ? "rail-item active" : "rail-item"} onClick={() => setCategory(item)} key={item}>{item}</button>)}</aside><section className="pos-catalog"><div className="pos-search"><Search size={16} /><input data-testid="pos-search-input" placeholder="Buscar item..." value={search} onChange={(event) => setSearch(event.target.value)} /></div>{visibleProducts.length === 0 ? <div data-testid="pos-products-empty" className="pos-empty"><h2>Nenhum produto em {category}</h2><p>Cadastre produtos nessa categoria para começar o atendimento.</p></div> : <div className="pos-card-grid">{visibleProducts.map((product) => <button data-testid={`pos-product-${product.id}`} className="pos-card" onClick={() => addToCart(product)} key={product.id}><span className="pos-card-badge">{product.category?.slice(0, 1)}</span><strong>{product.name}</strong><span className="pos-card-price">{money(productPrice(product))}</span></button>)}</div>}</section><aside className="pos-order"><div className="pos-order-head"><h2>Pedido</h2><span data-testid="pos-item-count">{itemCount} {itemCount === 1 ? "item" : "itens"}</span></div>{cart.length === 0 ? <div data-testid="pos-ticket-empty" className="pos-order-empty">Toque nos produtos para adicionar.</div> : <div className="pos-order-lines">{cart.map((line) => <div data-testid={`pos-cart-line-${line.id}`} className="pos-order-line" key={line.id}><div className="pos-line-info"><strong>{line.product_name}</strong><small>{money(line.unit_price)} cada</small></div><div className="pos-line-controls"><button data-testid={`pos-decrease-${line.id}`} onClick={() => changeQuantity(line.id, -1)} aria-label="Diminuir"><Minus size={13} /></button><b>{line.quantity}</b><button data-testid={`pos-increase-${line.id}`} onClick={() => changeQuantity(line.id, 1)} aria-label="Aumentar"><Plus size={13} /></button></div><span className="pos-line-total">{money(line.unit_price * line.quantity)}</span><button data-testid={`pos-remove-${line.id}`} className="pos-line-remove" onClick={() => setCart(cart.filter((item) => item.id !== line.id))} aria-label="Remover"><Trash2 size={14} /></button></div>)}</div>}{message && <p data-testid="pos-message" className="form-message">{message}</p>}<div className="pos-order-footer"><div className="pos-order-total"><span>Total</span><strong data-testid="pos-order-total">{money(total)}</strong></div><button data-testid="pos-finish-sale-button" className="pos-close-order" disabled={cart.length === 0} onClick={() => setCheckout(true)}>Fechar pedido</button></div></aside></div>;
}

export default function CrudModule({ type }) { return type === "recipes" ? <RecipeModule /> : type === "pos" ? <PosModule /> : <StandardModule type={type} />; }